---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "A Divine Service"
keywords:    "Divine, Cleaning, Services, jekyll, template, github, blog, single page"
description: "‘A cleaning service provided with divine care’"
source_link: "http://adivineservice.com"
favicon:     "img/favicon.ico" #put a path like: "img/favicon.ico"
touch_icon:  "img/logo.png" #put a path like: "img/apple-touch-icon.png"
google_analytics_key: UA-80740044-2 ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  teal:      '#008080'

kramdown:
  auto_ids:  false
